
// unicode_canonical_decomposer.h

#pragma once

#include <cstddef>
#include <cstdint>
#include <type_traits>

#include "unicode_decomposition.h"


namespace waavs
{
    // ========================================================================
    // Canonical decomposition limits
    //
    // Unicode 17.0.0 has a maximum fully recursive explicit canonical
    // decomposition length of four code points.
    //
    // Hangul canonical decomposition produces two or three code points.
    //
    // Four is therefore sufficient for the Unicode 17 database currently
    // generated by unicover. This is a database/version invariant rather than
    // an assumption that future Unicode versions can never exceed it.
    // ========================================================================

    static constexpr uint32_t kUnicodeCanonicalDecompositionMaxLength = 4;


    // ========================================================================
    // UnicodeCanonicalDecomposition
    //
    // Fixed-size result of recursively decomposing one Unicode code point.
    //
    // A valid input always produces at least one output code point:
    //
    //      no decomposition:
    //
    //          X -> X
    //
    //      singleton:
    //
    //          X -> A
    //
    //      pair:
    //
    //          X -> A B
    //
    //      recursive:
    //
    //          X -> A B
    //          A -> C D
    //
    //          result: C D B
    //
    //      Hangul:
    //
    //          S -> L V
    //          S -> L V T
    //
    // This structure performs no allocation and is suitable for stack use.
    // ========================================================================

    struct UnicodeCanonicalDecomposition
    {
        uint32_t codePoints[kUnicodeCanonicalDecompositionMaxLength]{};
        uint32_t count{ 0 };


        constexpr void clear() noexcept { count = 0; }

        [[nodiscard]] constexpr bool empty() const noexcept { return count == 0; }
        [[nodiscard]] constexpr size_t size() const noexcept { return count; }

        [[nodiscard]] constexpr uint32_t* data() noexcept { return codePoints; }
        [[nodiscard]] constexpr const uint32_t* data() const noexcept { return codePoints; }

        [[nodiscard]] constexpr uint32_t* begin() noexcept { return codePoints; }
        [[nodiscard]] constexpr const uint32_t* begin() const noexcept { return codePoints; }

        [[nodiscard]] constexpr uint32_t* end() noexcept { return codePoints + count; }
        [[nodiscard]] constexpr const uint32_t* end() const noexcept { return codePoints + count; }

        [[nodiscard]] constexpr uint32_t& operator[](size_t index) noexcept {
            return codePoints[index];
        }

        [[nodiscard]] constexpr const uint32_t& operator[](size_t index) const noexcept {
            return codePoints[index];
        }

        explicit constexpr operator bool() const noexcept { return count != 0; }
    };


    static_assert(
        std::is_trivially_copyable<UnicodeCanonicalDecomposition>::value,
        "UnicodeCanonicalDecomposition must be trivially copyable");

    static_assert(
        std::is_standard_layout<UnicodeCanonicalDecomposition>::value,
        "UnicodeCanonicalDecomposition must have standard layout");


    // ========================================================================
    // UnicodeCanonicalDecomposer
    //
    // Runtime implementation of full recursive canonical decomposition for
    // one Unicode code point.
    //
    // The decomposer consumes only UnicodeDecomposition rather than an entire
    // UnicodeDatabase. This keeps the Unicode algorithm independent of the
    // persistent database container.
    //
    // Typical use:
    //
    //      UnicodeCanonicalDecomposer decomposer(
    //          database.decomposition());
    //
    //      UnicodeCanonicalDecomposition result;
    //
    //      if (decomposer.decompose(0x01D5, result)) {
    //          ...
    //      }
    //
    // U+01D5:
    //
    //      U+01D5 -> U+00DC U+0304
    //      U+00DC -> U+0055 U+0308
    //
    // therefore:
    //
    //      U+01D5 -> U+0055 U+0308 U+0304
    //
    //
    // This class performs:
    //
    //      - direct canonical decomposition lookup
    //      - recursive canonical decomposition
    //      - algorithmic Hangul decomposition
    //
    // It deliberately does NOT perform:
    //
    //      - canonical combining-class ordering
    //      - canonical composition
    //      - NFD / NFC
    //
    // Canonical ordering is the next layer above this primitive.
    //
    // ========================================================================

    class UnicodeCanonicalDecomposer
    {
    public:
        UnicodeCanonicalDecomposer() noexcept = default;

        explicit UnicodeCanonicalDecomposer(UnicodeDecomposition decomposition) noexcept
            : mDecomposition(decomposition)
        {
        }


        // ====================================================================
        // State
        // ====================================================================

        [[nodiscard]] bool valid() const noexcept { return mDecomposition.valid(); }

        explicit operator bool() const noexcept { return valid(); }


        void reset(UnicodeDecomposition decomposition = {}) noexcept {
            mDecomposition = decomposition;
        }


        [[nodiscard]]
        const UnicodeDecomposition& decomposition() const noexcept {
            return mDecomposition;
        }


        // ====================================================================
        // decompose
        //
        // Fully recursively decompose one Unicode code point.
        //
        // outResult is changed only after complete success.
        //
        // Returns false when:
        //
        //      - the decomposition view is invalid
        //      - cp is outside the Unicode address space
        //      - recursive expansion exceeds the fixed result capacity
        //      - a malformed/cyclic decomposition exceeds the recursion guard
        //
        // For a valid code point with no canonical decomposition:
        //
        //      result.count         = 1
        //      result.codePoints[0] = cp
        //
        // ====================================================================

        [[nodiscard]]
        bool decompose(uint32_t cp, UnicodeCanonicalDecomposition& outResult) const noexcept
        {
            if (!mDecomposition.valid() || cp >= kUnicodeLimit)
                return false;

            UnicodeCanonicalDecomposition result;

            if (!decomposeRecursive(cp, result, 0))
                return false;

            outResult = result;
            return true;
        }


    private:
        // ====================================================================
        // Hangul constants
        //
        // Unicode canonical Hangul decomposition is algorithmic and therefore
        // does not require persistent decomposition records.
        //
        //      SBase = AC00
        //      LBase = 1100
        //      VBase = 1161
        //      TBase = 11A7
        //
        //      LCount = 19
        //      VCount = 21
        //      TCount = 28
        //
        //      NCount = VCount * TCount = 588
        //      SCount = LCount * NCount = 11172
        //
        // ====================================================================

        static constexpr uint32_t kHangulSBase = 0xAC00u;
        static constexpr uint32_t kHangulLBase = 0x1100u;
        static constexpr uint32_t kHangulVBase = 0x1161u;
        static constexpr uint32_t kHangulTBase = 0x11A7u;

        static constexpr uint32_t kHangulLCount = 19u;
        static constexpr uint32_t kHangulVCount = 21u;
        static constexpr uint32_t kHangulTCount = 28u;

        static constexpr uint32_t kHangulNCount =
            kHangulVCount * kHangulTCount;

        static constexpr uint32_t kHangulSCount =
            kHangulLCount * kHangulNCount;


        // ====================================================================
        // Recursion guard
        //
        // Unicode 17 canonical decomposition has a maximum explicit recursion
        // depth of three.
        //
        // The larger guard is not part of the Unicode representation. It is
        // simply defensive protection against a malformed manually-created
        // UnicodeDecomposition view containing a cycle.
        // ====================================================================

        static constexpr uint32_t kRecursionLimit = 32u;


        // ====================================================================
        // isHangulSyllable
        // ====================================================================

        [[nodiscard]]
        static constexpr bool isHangulSyllable(uint32_t cp) noexcept
        {
            return cp >= kHangulSBase &&
                cp < kHangulSBase + kHangulSCount;
        }


        // ====================================================================
        // append
        // ====================================================================

        [[nodiscard]]
        static bool append(uint32_t cp, UnicodeCanonicalDecomposition& result) noexcept
        {
            if (result.count >= kUnicodeCanonicalDecompositionMaxLength)
                return false;

            result.codePoints[result.count++] = cp;
            return true;
        }


        // ====================================================================
        // decomposeHangul
        //
        // Fully decompose a precomposed Hangul syllable directly to:
        //
        //      L V
        //
        // or:
        //
        //      L V T
        //
        // The generated Jamo do not themselves require further canonical
        // decomposition.
        // ====================================================================

        [[nodiscard]]
        static bool decomposeHangul(uint32_t cp,
            UnicodeCanonicalDecomposition& result) noexcept
        {
            const uint32_t sIndex =
                cp - kHangulSBase;

            const uint32_t l =
                kHangulLBase +
                sIndex / kHangulNCount;

            const uint32_t v =
                kHangulVBase +
                (sIndex % kHangulNCount) / kHangulTCount;

            const uint32_t tIndex =
                sIndex % kHangulTCount;


            if (!append(l, result))
                return false;

            if (!append(v, result))
                return false;

            if (tIndex != 0) {
                const uint32_t t =
                    kHangulTBase + tIndex;

                if (!append(t, result))
                    return false;
            }

            return true;
        }


        // ====================================================================
        // decomposeRecursive
        //
        // Recursively follow direct canonical-decomposition records until all
        // emitted code points are decomposition leaves.
        //
        // Both components of a pair are recursively processed. This matters
        // because canonical decomposition data is stored exactly as supplied
        // by the UCD rather than pre-flattened by unicover.
        // ====================================================================

        [[nodiscard]]
        bool decomposeRecursive(uint32_t cp,
            UnicodeCanonicalDecomposition& result,
            uint32_t depth) const noexcept
        {
            if (cp >= kUnicodeLimit)
                return false;

            if (depth >= kRecursionLimit)
                return false;


            // ---------------------------------------------------------------
            // Hangul syllables are decomposed algorithmically.
            // ---------------------------------------------------------------

            if (isHangulSyllable(cp))
                return decomposeHangul(cp, result);


            // ---------------------------------------------------------------
            // Explicit UCD canonical decomposition.
            // ---------------------------------------------------------------

            const UnicodeDecompositionRecord* record =
                mDecomposition.record(cp);


            // ---------------------------------------------------------------
            // No decomposition means this code point is a leaf.
            // ---------------------------------------------------------------

            if (!record)
                return append(cp, result);


            // ---------------------------------------------------------------
            // Recursively expand the first component.
            // ---------------------------------------------------------------

            if (!decomposeRecursive(
                record->first,
                result,
                depth + 1u))
            {
                return false;
            }


            // ---------------------------------------------------------------
            // Singleton mappings have no second component.
            // ---------------------------------------------------------------

            if (record->second == kUnicodeDecompositionSecondNone)
                return true;


            // ---------------------------------------------------------------
            // Recursively expand the second component.
            // ---------------------------------------------------------------

            return decomposeRecursive(
                record->second,
                result,
                depth + 1u);
        }


        UnicodeDecomposition mDecomposition{};
    };

} // namespace waavs
